# ✈️ Flight Price Prediction

# Notebook 03: Data Cleaning

## Objective

In this notebook, we will:

- Handle missing values
- Remove duplicate records
- Drop unnecessary columns
- Verify the cleaned dataset
- Save the cleaned dataset for the next phase

In [1]:
import warnings
warnings.filterwarnings("ignore")

from pathlib import Path
import pandas as pd

pd.set_option("display.max_columns", None)

In [2]:
DATA_DIR = Path("../data/raw")

df = pd.read_excel(DATA_DIR / "Train.xlsx")

df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [3]:
print("Missing Values:\n")
df.isnull().sum()

Missing Values:

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

In [4]:
df.dropna(inplace=True)

print("Dataset Shape:", df.shape)

Dataset Shape: (10682, 11)

In [5]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 220

In [6]:
df.drop_duplicates(inplace=True)

print("Dataset Shape After Removing Duplicates:", df.shape)

Dataset Shape After Removing Duplicates: (10462, 11)

In [7]:
df["Additional_Info"].value_counts()

Additional_Info
No info                         8182
In-flight meal not included     1926
No check-in baggage included     318
1 Long layover                    19
Change airports                    7
Business class                     4
No Info                            3
1 Short layover                    1
Red-eye flight                     1
2 Long layover                     1
Name: count, dtype: int64

In [8]:
df.drop(columns=["Additional_Info"], inplace=True)

df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,13302

In [9]:
print("Final Shape:", df.shape)

print("\nMissing Values:\n")
print(df.isnull().sum())

print("\nDuplicate Rows:", df.duplicated().sum())

Final Shape: (10462, 10)

Missing Values:

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              0
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        0
Price              0
dtype: int64

Duplicate Rows: 0

In [10]:
PROCESSED_DIR = Path("../data/processed")
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

df.to_csv(PROCESSED_DIR / "cleaned_train.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

# Data Cleaning Summary

### Completed Tasks

- Removed missing values
- Removed duplicate records
- Dropped the `Additional_Info` column
- Saved the cleaned dataset

The dataset is now ready for **Feature Engineering**, where we will extract useful numerical features from dates, times, and durations.